// Mocks generated by Mockito 5.4.6 from annotations
// in quanlyshop/test/advanced_analytics_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:quanlyshop/data/db_helper.dart' as _i3;
import 'package:quanlyshop/models/attendance_model.dart' as _i10;
import 'package:quanlyshop/models/debt_model.dart' as _i9;
import 'package:quanlyshop/models/expense_model.dart' as _i8;
import 'package:quanlyshop/models/product_model.dart' as _i7;
import 'package:quanlyshop/models/purchase_order_model.dart' as _i11;
import 'package:quanlyshop/models/quick_input_code_model.dart' as _i13;
import 'package:quanlyshop/models/repair_model.dart' as _i5;
import 'package:quanlyshop/models/sale_order_model.dart' as _i6;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DBHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDBHelper extends _i1.Mock implements _i3.DBHelper {
  MockDBHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  _i4.Future<void> upsertRepair(_i5.Repair? r) =>
      (super.noSuchMethod(
            Invocation.method(#upsertRepair, [r]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> insertRepair(_i5.Repair? r) =>
      (super.noSuchMethod(
            Invocation.method(#insertRepair, [r]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateRepair(_i5.Repair? r) =>
      (super.noSuchMethod(
            Invocation.method(#updateRepair, [r]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteRepair(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRepair, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteRepairByFirestoreId(String? fId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRepairByFirestoreId, [fId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.Repair>> getAllRepairs() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRepairs, []),
            returnValue: _i4.Future<List<_i5.Repair>>.value(<_i5.Repair>[]),
          )
          as _i4.Future<List<_i5.Repair>>);

  @override
  _i4.Future<_i5.Repair?> getRepairById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRepairById, [id]),
            returnValue: _i4.Future<_i5.Repair?>.value(),
          )
          as _i4.Future<_i5.Repair?>);

  @override
  _i4.Future<_i5.Repair?> getRepairByFirestoreId(String? firestoreId) =>
      (super.noSuchMethod(
            Invocation.method(#getRepairByFirestoreId, [firestoreId]),
            returnValue: _i4.Future<_i5.Repair?>.value(),
          )
          as _i4.Future<_i5.Repair?>);

  @override
  _i4.Future<List<_i5.Repair>> getRepairsByImei(String? imei) =>
      (super.noSuchMethod(
            Invocation.method(#getRepairsByImei, [imei]),
            returnValue: _i4.Future<List<_i5.Repair>>.value(<_i5.Repair>[]),
          )
          as _i4.Future<List<_i5.Repair>>);

  @override
  _i4.Future<void> upsertSale(_i6.SaleOrder? s) =>
      (super.noSuchMethod(
            Invocation.method(#upsertSale, [s]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> insertSale(_i6.SaleOrder? s) =>
      (super.noSuchMethod(
            Invocation.method(#insertSale, [s]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateSale(_i6.SaleOrder? s) =>
      (super.noSuchMethod(
            Invocation.method(#updateSale, [s]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteSale(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSale, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteSaleByFirestoreId(String? fId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSaleByFirestoreId, [fId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i6.SaleOrder>> getAllSales() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSales, []),
            returnValue: _i4.Future<List<_i6.SaleOrder>>.value(
              <_i6.SaleOrder>[],
            ),
          )
          as _i4.Future<List<_i6.SaleOrder>>);

  @override
  _i4.Future<_i6.SaleOrder?> getSaleByFirestoreId(String? firestoreId) =>
      (super.noSuchMethod(
            Invocation.method(#getSaleByFirestoreId, [firestoreId]),
            returnValue: _i4.Future<_i6.SaleOrder?>.value(),
          )
          as _i4.Future<_i6.SaleOrder?>);

  @override
  _i4.Future<void> upsertProduct(_i7.Product? p) =>
      (super.noSuchMethod(
            Invocation.method(#upsertProduct, [p]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> updateProduct(_i7.Product? p) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [p]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteProductByFirestoreId(String? fId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProductByFirestoreId, [fId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i7.Product>> getInStockProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getInStockProducts, []),
            returnValue: _i4.Future<List<_i7.Product>>.value(<_i7.Product>[]),
          )
          as _i4.Future<List<_i7.Product>>);

  @override
  _i4.Future<List<_i7.Product>> getAllProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProducts, []),
            returnValue: _i4.Future<List<_i7.Product>>.value(<_i7.Product>[]),
          )
          as _i4.Future<List<_i7.Product>>);

  @override
  _i4.Future<_i7.Product?> getProductByFirestoreId(String? firestoreId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductByFirestoreId, [firestoreId]),
            returnValue: _i4.Future<_i7.Product?>.value(),
          )
          as _i4.Future<_i7.Product?>);

  @override
  _i4.Future<_i7.Product?> getProductById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i4.Future<_i7.Product?>.value(),
          )
          as _i4.Future<_i7.Product?>);

  @override
  _i4.Future<int> updateProductStatus(int? id, int? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateProductStatus, [id, status]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> deductProductQuantity(int? id, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#deductProductQuantity, [id, amount]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.Product?> getProductByImei(String? imei) =>
      (super.noSuchMethod(
            Invocation.method(#getProductByImei, [imei]),
            returnValue: _i4.Future<_i7.Product?>.value(),
          )
          as _i4.Future<_i7.Product?>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getCustomerSuggestions() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerSuggestions, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getUniqueCustomersAll() =>
      (super.noSuchMethod(
            Invocation.method(#getUniqueCustomersAll, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getCustomersWithoutShop() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomersWithoutShop, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> deleteCustomerData(String? name, String? phone) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCustomerData, [name, phone]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> deleteCustomerByPhone(String? phone) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCustomerByPhone, [phone]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> insertSupplier(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#insertSupplier, [map]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getSuppliers() =>
      (super.noSuchMethod(
            Invocation.method(#getSuppliers, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> deleteSupplier(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSupplier, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> upsertExpense(_i8.Expense? e) =>
      (super.noSuchMethod(
            Invocation.method(#upsertExpense, [e]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> insertExpense(Map<String, dynamic>? e) =>
      (super.noSuchMethod(
            Invocation.method(#insertExpense, [e]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllExpenses() =>
      (super.noSuchMethod(
            Invocation.method(#getAllExpenses, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> deleteExpenseByFirestoreId(String? fId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExpenseByFirestoreId, [fId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> upsertDebt(_i9.Debt? d) =>
      (super.noSuchMethod(
            Invocation.method(#upsertDebt, [d]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> insertDebt(Map<String, dynamic>? d) =>
      (super.noSuchMethod(
            Invocation.method(#insertDebt, [d]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllDebts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDebts, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getPurchaseDebts() =>
      (super.noSuchMethod(
            Invocation.method(#getPurchaseDebts, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> updateDebtPaid(int? id, int? pay) =>
      (super.noSuchMethod(
            Invocation.method(#updateDebtPaid, [id, pay]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateDebt(Map<String, dynamic>? debt) =>
      (super.noSuchMethod(
            Invocation.method(#updateDebt, [debt]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteDebtByFirestoreId(String? fId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDebtByFirestoreId, [fId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> upsertClosing(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#upsertClosing, [map]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> upsertAttendance(_i10.Attendance? a) =>
      (super.noSuchMethod(
            Invocation.method(#upsertAttendance, [a]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> insertAttendance(_i10.Attendance? a) =>
      (super.noSuchMethod(
            Invocation.method(#insertAttendance, [a]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateAttendance(_i10.Attendance? a) =>
      (super.noSuchMethod(
            Invocation.method(#updateAttendance, [a]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteAttendanceByFirestoreId(String? fId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAttendanceByFirestoreId, [fId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i10.Attendance>> getAllAttendance() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAttendance, []),
            returnValue: _i4.Future<List<_i10.Attendance>>.value(
              <_i10.Attendance>[],
            ),
          )
          as _i4.Future<List<_i10.Attendance>>);

  @override
  _i4.Future<_i10.Attendance?> getAttendance(String? dateKey, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getAttendance, [dateKey, userId]),
            returnValue: _i4.Future<_i10.Attendance?>.value(),
          )
          as _i4.Future<_i10.Attendance?>);

  @override
  _i4.Future<List<_i10.Attendance>> getAttendanceByUser(
    String? userId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAttendanceByUser, [userId], {#limit: limit}),
            returnValue: _i4.Future<List<_i10.Attendance>>.value(
              <_i10.Attendance>[],
            ),
          )
          as _i4.Future<List<_i10.Attendance>>);

  @override
  _i4.Future<List<_i10.Attendance>> getAttendanceByDateRange(
    String? start,
    String? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAttendanceByDateRange, [start, end]),
            returnValue: _i4.Future<List<_i10.Attendance>>.value(
              <_i10.Attendance>[],
            ),
          )
          as _i4.Future<List<_i10.Attendance>>);

  @override
  _i4.Future<Map<String, dynamic>?> getWorkSchedule(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkSchedule, [userId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> upsertWorkSchedule(
    String? userId,
    Map<String, dynamic>? schedule,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsertWorkSchedule, [userId, schedule]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i11.PurchaseOrder>> getAllPurchaseOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPurchaseOrders, []),
            returnValue: _i4.Future<List<_i11.PurchaseOrder>>.value(
              <_i11.PurchaseOrder>[],
            ),
          )
          as _i4.Future<List<_i11.PurchaseOrder>>);

  @override
  _i4.Future<String> generateNextOrderCode() =>
      (super.noSuchMethod(
            Invocation.method(#generateNextOrderCode, []),
            returnValue: _i4.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#generateNextOrderCode, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> insertPurchaseOrder(_i11.PurchaseOrder? order) =>
      (super.noSuchMethod(
            Invocation.method(#insertPurchaseOrder, [order]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePurchaseOrder(_i11.PurchaseOrder? order) =>
      (super.noSuchMethod(
            Invocation.method(#updatePurchaseOrder, [order]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getInventoryChecks({
    String? checkType,
    bool? isCompleted,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getInventoryChecks, [], {
              #checkType: checkType,
              #isCompleted: isCompleted,
            }),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> insertInventoryCheck(dynamic data) =>
      (super.noSuchMethod(
            Invocation.method(#insertInventoryCheck, [data]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateInventoryCheck(dynamic data) =>
      (super.noSuchMethod(
            Invocation.method(#updateInventoryCheck, [data]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getItemsForInventoryCheck(
    String? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getItemsForInventoryCheck, [type]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllParts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllParts, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> insertPart(Map<String, dynamic>? part) =>
      (super.noSuchMethod(
            Invocation.method(#insertPart, [part]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> logAction({
    required String? userId,
    required String? userName,
    required String? action,
    required String? type,
    String? targetId,
    String? desc,
    String? fId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logAction, [], {
              #userId: userId,
              #userName: userName,
              #action: action,
              #type: type,
              #targetId: targetId,
              #desc: desc,
              #fId: fId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAuditLogs() =>
      (super.noSuchMethod(
            Invocation.method(#getAuditLogs, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> getPayrollSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getPayrollSettings, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> savePayrollSettings(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#savePayrollSettings, [data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isPayrollMonthLocked(String? monthKey) =>
      (super.noSuchMethod(
            Invocation.method(#isPayrollMonthLocked, [monthKey]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> setPayrollMonthLock(
    String? monthKey, {
    required bool? locked,
    String? lockedBy,
    String? note,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setPayrollMonthLock,
              [monthKey],
              {#locked: locked, #lockedBy: lockedBy, #note: note},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getPayrollLocks({int? limit = 100}) =>
      (super.noSuchMethod(
            Invocation.method(#getPayrollLocks, [], {#limit: limit}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> updateOrderStatusFromDebt(
    String? linkedId,
    int? newPaidAmount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderStatusFromDebt, [
              linkedId,
              newPaidAmount,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cleanDuplicateData() =>
      (super.noSuchMethod(
            Invocation.method(#cleanDuplicateData, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> insertDebtPayment(Map<String, dynamic>? p) =>
      (super.noSuchMethod(
            Invocation.method(#insertDebtPayment, [p]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getDebtPayments(int? debtId) =>
      (super.noSuchMethod(
            Invocation.method(#getDebtPayments, [debtId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllDebtPaymentsWithDetails() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDebtPaymentsWithDetails, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<_i13.QuickInputCode>> getQuickInputCodes() =>
      (super.noSuchMethod(
            Invocation.method(#getQuickInputCodes, []),
            returnValue: _i4.Future<List<_i13.QuickInputCode>>.value(
              <_i13.QuickInputCode>[],
            ),
          )
          as _i4.Future<List<_i13.QuickInputCode>>);

  @override
  _i4.Future<int> insertQuickInputCode(_i13.QuickInputCode? code) =>
      (super.noSuchMethod(
            Invocation.method(#insertQuickInputCode, [code]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateQuickInputCode(_i13.QuickInputCode? code) =>
      (super.noSuchMethod(
            Invocation.method(#updateQuickInputCode, [code]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteQuickInputCode(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteQuickInputCode, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> toggleQuickInputCodeActive(int? id, bool? isActive) =>
      (super.noSuchMethod(
            Invocation.method(#toggleQuickInputCodeActive, [id, isActive]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteQuickInputCodeByFirestoreId(String? fId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteQuickInputCodeByFirestoreId, [fId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> upsertQuickInputCode(_i13.QuickInputCode? code) =>
      (super.noSuchMethod(
            Invocation.method(#upsertQuickInputCode, [code]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i13.QuickInputCode>> getUnsyncedQuickInputCodes() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedQuickInputCodes, []),
            returnValue: _i4.Future<List<_i13.QuickInputCode>>.value(
              <_i13.QuickInputCode>[],
            ),
          )
          as _i4.Future<List<_i13.QuickInputCode>>);

  @override
  _i4.Future<int> getUnsyncedQuickInputCodesCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedQuickInputCodesCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> insertSupplierProductPrice(Map<String, dynamic>? price) =>
      (super.noSuchMethod(
            Invocation.method(#insertSupplierProductPrice, [price]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> updateSupplierProductPrice(
    int? id,
    Map<String, dynamic>? price,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSupplierProductPrice, [id, price]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getSupplierProductPrices(
    int? supplierId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSupplierProductPrices, [supplierId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getSupplierProductPrice(
    int? supplierId,
    String? productName,
    String? productBrand,
    String? productModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSupplierProductPrice, [
              supplierId,
              productName,
              productBrand,
              productModel,
            ]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<int> deactivateSupplierProductPrice(
    int? supplierId,
    String? productName,
    String? productBrand,
    String? productModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deactivateSupplierProductPrice, [
              supplierId,
              productName,
              productBrand,
              productModel,
            ]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> insertSupplierImportHistory(Map<String, dynamic>? history) =>
      (super.noSuchMethod(
            Invocation.method(#insertSupplierImportHistory, [history]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getSupplierImportHistory(
    int? supplierId, {
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSupplierImportHistory,
              [supplierId],
              {#limit: limit, #offset: offset},
            ),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getSupplierImportHistoryByDateRange(
    int? supplierId,
    int? startDate,
    int? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSupplierImportHistoryByDateRange, [
              supplierId,
              startDate,
              endDate,
            ]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getSupplierImportStats(int? supplierId) =>
      (super.noSuchMethod(
            Invocation.method(#getSupplierImportStats, [supplierId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getUnsyncedSupplierImportHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedSupplierImportHistory, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> markSupplierImportHistorySynced(String? firestoreId) =>
      (super.noSuchMethod(
            Invocation.method(#markSupplierImportHistorySynced, [firestoreId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> updateSupplierStats(int? supplierId) =>
      (super.noSuchMethod(
            Invocation.method(#updateSupplierStats, [supplierId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getRepairPartners() =>
      (super.noSuchMethod(
            Invocation.method(#getRepairPartners, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> insertRepairPartner(Map<String, dynamic>? partner) =>
      (super.noSuchMethod(
            Invocation.method(#insertRepairPartner, [partner]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updateRepairPartner(int? id, Map<String, dynamic>? partner) =>
      (super.noSuchMethod(
            Invocation.method(#updateRepairPartner, [id, partner]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteRepairPartner(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRepairPartner, [id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> insertPartnerRepairHistory(Map<String, dynamic>? history) =>
      (super.noSuchMethod(
            Invocation.method(#insertPartnerRepairHistory, [history]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> updatePartnerRepairHistory(
    int? id,
    Map<String, dynamic>? history,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePartnerRepairHistory, [id, history]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getPartnerRepairHistory({
    int? partnerId,
    String? repairOrderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPartnerRepairHistory, [], {
              #partnerId: partnerId,
              #repairOrderId: repairOrderId,
            }),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getPartnerRepairStats(int? partnerId) =>
      (super.noSuchMethod(
            Invocation.method(#getPartnerRepairStats, [partnerId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);
}
