const { initializeTestEnvironment, assertSucceeds, assertFails } = require('@firebase/rules-unit-testing');
const { doc, setDoc, getDoc, updateDoc, deleteDoc, collection, getDocs, query, where } = require('firebase/firestore');
const fs = require('fs');
(async () => {
  const env = await initializeTestEnvironment({ projectId: 'huyaka-1809',
    firestore: { rules: fs.readFileSync('firestore.rules','utf8'), host: '127.0.0.1', port: 8089 } });
  const OA='ownerA', OB='ownerB', EA='empA', SA='A', SB='B';
  await env.withSecurityRulesDisabled(async (ctx) => { const db = ctx.firestore();
    await setDoc(doc(db,'shops',SA), { ownerUid: OA, name:'A' });
    await setDoc(doc(db,'shops',SB), { ownerUid: OB, name:'B' });
    await setDoc(doc(db,'users',OA), { role:'owner', shopId: SA });
    await setDoc(doc(db,'users',OB), { role:'owner', shopId: SB });
    await setDoc(doc(db,'users',EA), { role:'user', shopId: SA, allowViewSales:false });
    await setDoc(doc(db,'repairs','rB'), { shopId: SB, model:'X', issue:'Y', createdAt: 1, status: 1 });
    await setDoc(doc(db,'sales','sB'), { shopId: SB, customerName:'C', productNames:'P', totalPrice: 1, soldAt: 1 });
    await setDoc(doc(db,'sales','sA'), { shopId: SA, customerName:'C', productNames:'P', totalPrice: 1, soldAt: 1 });
    await setDoc(doc(db,'debts','dB'), { shopId: SB, personName:'x', totalAmount: 1 });
    await setDoc(doc(db,'products','pB'), { shopId: SB, name:'x', quantity: 1 });
  });
  const a = env.authenticatedContext(OA, { role:'owner', shopId: SA }).firestore();
  const e = env.authenticatedContext(EA, { role:'user', shopId: SA }).firestore();
  const T = async (name, pr, ok) => { try { await (ok ? assertSucceeds(pr) : assertFails(pr)); console.log('PASS', name); } catch (x) { console.log('FAIL', name, ok?'(should allow)':'(should deny)'); } };
  await T('PERM-03 ownerA read repairs shop B', getDoc(doc(a,'repairs','rB')), false);
  await T('PERM-03b ownerA read sales shop B', getDoc(doc(a,'sales','sB')), false);
  await T('PERM-03c ownerA read debts shop B', getDoc(doc(a,'debts','dB')), false);
  await T('PERM-03d ownerA query sales where shopId=B', getDocs(query(collection(a,'sales'), where('shopId','==',SB))), false);
  await T('PERM-03e ownerA query sales where shopId=A', getDocs(query(collection(a,'sales'), where('shopId','==',SA))), true);
  await T('PERM-04 ownerA create repair with shopId B', setDoc(doc(a,'repairs','rA2'), { shopId: SB, model:'X', issue:'Y', createdAt: 1, status: 1 }), false);
  await T('PERM-04b ownerA create repair shopId A', setDoc(doc(a,'repairs','rA1'), { shopId: SA, model:'X', issue:'Y', createdAt: 1, status: 1 }), true);
  await T('PERM-05 ownerA update shopId of own sale to B', updateDoc(doc(a,'sales','sA'), { shopId: SB }), false);
  await T('PERM-05b ownerA update product of shop B', updateDoc(doc(a,'products','pB'), { quantity: 0 }), false);
  await T('PERM-06 employee(user role, no allowViewSales) create sale', setDoc(doc(e,'sales','sE'), { shopId: SA, customerName:'C', productNames:'P', totalPrice: 1, soldAt: 1 }), false);
  await T('PERM-06b employee delete sale', deleteDoc(doc(e,'sales','sA')), false);
  await T('PERM-06c employee create repair (allowed for all members)', setDoc(doc(e,'repairs','rE'), { shopId: SA, model:'X', issue:'Y', createdAt: 1, status: 1 }), true);
  await T('PERM-06d employee read debts shop A', getDoc(doc(a,'debts','dB')), false);
  await T('PERM-08 write shop_chats (no rule)', setDoc(doc(a,'shop_chats','x'), { shopId: SA }), false);
  await T('PERM-12 repairs status 5 (invalid)', setDoc(doc(a,'repairs','rA3'), { shopId: SA, model:'X', issue:'Y', createdAt: 1, status: 5 }), false);
  await T('PERM-13 repairs negative price', setDoc(doc(a,'repairs','rA4'), { shopId: SA, model:'X', issue:'Y', createdAt: 1, status: 1, price: -5 }), false);
  await T('PERM-14 sales negative totalPrice', setDoc(doc(a,'sales','sA5'), { shopId: SA, customerName:'C', productNames:'P', totalPrice: -1, soldAt: 1 }), false);
  await T('PERM-15 supplier_debts write (legacy collection) by owner', setDoc(doc(a,'supplier_debts','x'), { shopId: SA, amount: 1 }), true);
  await T('PERM-16 financial_activities write by owner', setDoc(doc(a,'financial_activities','x'), { shopId: SA, amount: 1 }), true);
  await env.cleanup(); process.exit(0);
})();
