/**
 * Build mapping: hardcoded VI string → {key, en, vi, isNew}
 * Step 1: check if VI string already exists as ARB value → use that key
 * Step 2: manual mapping for common strings
 */
const fs = require('fs');
const vi = JSON.parse(fs.readFileSync('lib/l10n/app_vi.arb','utf8'));
const en = JSON.parse(fs.readFileSync('lib/l10n/app_en.arb','utf8'));
const viStrings = JSON.parse(fs.readFileSync('scripts/vi_strings.json','utf8'));

// Reverse map: vi value → key
const viValueToKey = {};
for (const [k, v] of Object.entries(vi)) {
  if (k.startsWith('@')) continue;
  if (typeof v === 'string') {
    viValueToKey[v] = k;
    viValueToKey[v.toUpperCase()] = k;
    viValueToKey[v.toLowerCase()] = k;
  }
}

// Additional manual mappings for top strings not in ARB
// Format: 'VI text': {key, en}
const manual = {
  'TIỀN MẶT': {key: 'paymentCash', en: 'CASH'},
  'Tiền mặt': {key: 'paymentCashLower', en: 'Cash'},
  'CÔNG NỢ': {key: 'debtUpper', en: 'DEBT'},
  'Công nợ': {key: 'debtLabel', en: 'Debt'},
  'HỦY': {key: 'cancelUpper', en: 'CANCEL'},
  'CHUYỂN KHOẢN': {key: 'paymentTransfer', en: 'TRANSFER'},
  'Chuyển khoản': {key: 'paymentTransferLower', en: 'Transfer'},
  'Ghi chú': {key: 'note', en: 'Note'},
  'Nhân viên': {key: 'staff', en: 'Staff'},
  'Tất cả': {key: 'all', en: 'All'},
  'TẤT CẢ': {key: 'allUpper', en: 'ALL'},
  'Xóa': {key: 'delete', en: 'Delete'},
  'XÓA': {key: 'deleteUpper', en: 'DELETE'},
  'Số điện thoại': {key: 'phone', en: 'Phone number'},
  'XÁC NHẬN': {key: 'confirmUpper', en: 'CONFIRM'},
  'Còn nợ': {key: 'remaining', en: 'Outstanding'},
  'Địa chỉ': {key: 'address', en: 'Address'},
  'LƯU': {key: 'saveUpper', en: 'SAVE'},
  'XÓA': {key: 'deleteUpper', en: 'DELETE'},
  'Sửa chữa': {key: 'repair', en: 'Repair'},
  'PHỤ KIỆN': {key: 'accessoryUpper', en: 'ACCESSORY'},
  'Phụ kiện': {key: 'accessory', en: 'Accessory'},
  'Chi phí': {key: 'expense', en: 'Expense'},
  'Nhà cung cấp': {key: 'supplier', en: 'Supplier'},
  'Làm mới': {key: 'refresh', en: 'Refresh'},
  'Chủ shop': {key: 'shopOwner', en: 'Shop owner'},
  'Quản lý': {key: 'manager', en: 'Manager'},
  'KHÁC': {key: 'otherUpper', en: 'OTHER'},
  'Khác': {key: 'other', en: 'Other'},
  'PHÁT SINH': {key: 'incidentalUpper', en: 'INCIDENTAL'},
  'Khách hàng': {key: 'customerLabel', en: 'Customer'},
  'TRẢ GÓP (NH)': {key: 'bankInstallment', en: 'BANK INSTALLMENT'},
  'Thử lại': {key: 'retry', en: 'Retry'},
  'Kỹ thuật': {key: 'technician', en: 'Technician'},
  'Thanh toán': {key: 'payment', en: 'Payment'},
  'Màu sắc': {key: 'color', en: 'Color'},
  'Xác nhận xóa': {key: 'confirmDelete', en: 'Confirm delete'},
  'XÁC NHẬN XÓA': {key: 'confirmDeleteUpper', en: 'CONFIRM DELETE'},
  'Tải lại': {key: 'reload', en: 'Reload'},
  'ĐÓNG': {key: 'closeUpper', en: 'CLOSE'},
  'Sửa': {key: 'edit', en: 'Edit'},
  'SỬA': {key: 'editUpper', en: 'EDIT'},
  'Xuất Excel': {key: 'exportExcel', en: 'Export Excel'},
  'Số tiền': {key: 'amount', en: 'Amount'},
  'Giá vốn': {key: 'costPrice', en: 'Cost price'},
  'Tình trạng': {key: 'condition', en: 'Condition'},
  'Thêm': {key: 'add', en: 'Add'},
  'THÊM': {key: 'addUpper', en: 'ADD'},
  'Xác nhận': {key: 'confirm', en: 'Confirm'},
  'Dung lượng': {key: 'storage', en: 'Storage'},
  'Đơn sửa chữa': {key: 'repairOrder', en: 'Repair order'},
  'Nhập hàng': {key: 'stockIn', en: 'Stock in'},
  'Đã trả': {key: 'paid', en: 'Paid'},
  'NGÀY': {key: 'dayUpper', en: 'DAY'},
  'Đang sửa': {key: 'repairing', en: 'Repairing'},
  'Sản phẩm': {key: 'product', en: 'Product'},
  'Đơn bán hàng': {key: 'saleOrder', en: 'Sale order'},
  'Không xác định': {key: 'unknown', en: 'Unknown'},
  'Hôm nay': {key: 'today', en: 'Today'},
  'HÔM NAY': {key: 'todayUpper', en: 'TODAY'},
  '7 ngày': {key: 'last7days', en: '7 days'},
  'Tháng này': {key: 'thisMonth', en: 'This month'},
  'KẾT HỢP': {key: 'combined', en: 'COMBINED'},
  'Bán hàng': {key: 'sales', en: 'Sales'},
  'SĐT': {key: 'phoneShort', en: 'Phone'},
  'Số lượng': {key: 'quantity', en: 'Quantity'},
  'TUẦN': {key: 'weekUpper', en: 'WEEK'},
  'Chưa chọn': {key: 'notSelected', en: 'Not selected'},
  'Bảo hành': {key: 'warrantyLabel', en: 'Warranty'},
  'Giá bán': {key: 'salePrice', en: 'Sale price'},
  'Đã tất toán': {key: 'settled', en: 'Settled'},
  'Đăng xuất': {key: 'logout', en: 'Logout'},
  'Đã thanh toán': {key: 'paymentDone', en: 'Paid'},
  'Khách lẻ': {key: 'retailCustomer', en: 'Retail customer'},
  'CẬP NHẬT': {key: 'updateUpper', en: 'UPDATE'},
  'Mã nhập nhanh': {key: 'quickCode', en: 'Quick code'},
  'HOÀN TIỀN': {key: 'refundUpper', en: 'REFUND'},
  'Phương thức thanh toán': {key: 'paymentMethod', en: 'Payment method'},
  'C.KHOẢN': {key: 'transferShort', en: 'Transfer'},
  'Quá hạn': {key: 'overdue', en: 'Overdue'},
  'ĐIỆN NƯỚC': {key: 'utilities', en: 'UTILITIES'},
  'Điện thoại': {key: 'phoneLabel', en: 'Phone'},
  'Vui lòng đăng nhập lại': {key: 'pleaseLoginAgain', en: 'Please login again'},
  'Đã bán': {key: 'sold', en: 'Sold'},
  'CHỦ SHOP': {key: 'ownerUpper', en: 'OWNER'},
  'QUẢN LÝ': {key: 'managerUpper', en: 'MANAGER'},
  'NHÂN VIÊN': {key: 'staffUpper', en: 'STAFF'},
  'KỸ THUẬT': {key: 'techUpper', en: 'TECH'},
  'Hoạt động': {key: 'active', en: 'Active'},
  'Đã nhận': {key: 'received', en: 'Received'},
  'Chờ duyệt': {key: 'pendingApproval', en: 'Pending approval'},
  'Từ chối': {key: 'reject', en: 'Reject'},
  'Đơn bán': {key: 'saleOrderShort', en: 'Sale'},
  'Chấm công': {key: 'attendance', en: 'Attendance'},
  'Tùy chọn': {key: 'options', en: 'Options'},
  'Trả nợ NCC': {key: 'paySupplierDebt', en: 'Pay supplier debt'},
  'Trả hàng': {key: 'returnGoods', en: 'Return goods'},
  'Thêm ảnh': {key: 'addPhoto', en: 'Add photo'},
  'Chọn từ thư viện': {key: 'chooseFromGallery', en: 'Choose from gallery'},
  'Lỗi đồng bộ': {key: 'syncErrorLabel', en: 'Sync error'},
  'NHẬP KHO': {key: 'stockInUpper', en: 'STOCK IN'},
  'THANH TOÁN': {key: 'paymentUpper', en: 'PAYMENT'},
  'Đang đồng bộ...': {key: 'syncing', en: 'Syncing...'},
  'Tổng nợ': {key: 'totalDebt', en: 'Total debt'},
  'Có lỗi xảy ra': {key: 'errorOccurred', en: 'An error occurred'},
  'Phải trả': {key: 'payable', en: 'Payable'},
  'CÁ NHÂN': {key: 'personal', en: 'PERSONAL'},
  'DỊCH VỤ': {key: 'service', en: 'SERVICE'},
  'Bật/tắt đèn flash': {key: 'toggleFlash', en: 'Toggle flash'},
  'Giá bán (VNĐ)': {key: 'salePriceVnd', en: 'Sale price (VND)'},
  'Khấu trừ': {key: 'deduction', en: 'Deduction'},
  'Lợi nhuận': {key: 'profit', en: 'Profit'},
  'Giá nhập (VNĐ)': {key: 'costPriceVnd', en: 'Cost price (VND)'},
  'Đang lưu...': {key: 'saving', en: 'Saving...'},
  'Ngừng HĐ': {key: 'deactivate', en: 'Deactivate'},
  'Thêm NCC mới': {key: 'addNewSupplier', en: 'Add new supplier'},
  'Shop không tên': {key: 'noShopName', en: 'Unnamed shop'},
  'Người dùng': {key: 'user', en: 'User'},
  'Tổng tiền': {key: 'totalAmount', en: 'Total amount'},
  'Chỉnh sửa': {key: 'editLabel', en: 'Edit'},
  'Đã giao': {key: 'delivered', en: 'Delivered'},
  'Xem chi tiết': {key: 'viewDetail', en: 'View detail'},
  'Lý do từ chối': {key: 'rejectReason', en: 'Reject reason'},
  'Trạng thái': {key: 'status', en: 'Status'},
  'Tải thêm': {key: 'loadMore', en: 'Load more'},
  'Mô tả': {key: 'description', en: 'Description'},
  'NHẬP': {key: 'importUpper', en: 'IMPORT'},
  'BÁN': {key: 'sellUpper', en: 'SELL'},
  'Tài chính': {key: 'financeLabel', en: 'Finance'},
  'Thanh toán nợ': {key: 'payDebt', en: 'Pay debt'},
  'Cài đặt lương': {key: 'salarySettings', en: 'Salary settings'},
  'Hệ thống': {key: 'system', en: 'System'},
  'Khôi phục': {key: 'restore', en: 'Restore'},
  'Đang xử lý...': {key: 'processing', en: 'Processing...'},
  'Chọn tất cả': {key: 'selectAll', en: 'Select all'},
  'Xem tất cả': {key: 'viewAll', en: 'View all'},
  'Chi tiết': {key: 'detail', en: 'Detail'},
  'Thu phát sinh': {key: 'incidentalIncome', en: 'Incidental income'},
  'Mới': {key: 'newLabel', en: 'New'},
  'KHÁCH VÃNG LAI': {key: 'walkInCustomer', en: 'WALK-IN CUSTOMER'},
  'Tên sản phẩm': {key: 'productName', en: 'Product name'},
  'Tìm kiếm': {key: 'search', en: 'Search'},
  'Danh sách': {key: 'list', en: 'List'},
  'Không có dữ liệu': {key: 'noData', en: 'No data'},
  'Chọn': {key: 'select', en: 'Select'},
  'Ngày': {key: 'date', en: 'Date'},
  'Tháng': {key: 'month', en: 'Month'},
  'Năm': {key: 'year', en: 'Year'},
  'Giờ': {key: 'hour', en: 'Hour'},
  'Phút': {key: 'minute', en: 'Minute'},
  'Tên': {key: 'name', en: 'Name'},
  'Loại': {key: 'type', en: 'Type'},
  'Tổng': {key: 'total', en: 'Total'},
  'Tuần': {key: 'week', en: 'Week'},
  'Ngày tháng': {key: 'dateTime', en: 'Date'},
  'Bộ lọc': {key: 'filter', en: 'Filter'},
  'Xuất': {key: 'export', en: 'Export'},
  'In': {key: 'print', en: 'Print'},
  'Chia sẻ': {key: 'share', en: 'Share'},
  'Sao chép': {key: 'copy', en: 'Copy'},
  'Gửi': {key: 'send', en: 'Send'},
  'Nhận': {key: 'receive', en: 'Receive'},
  'Xem': {key: 'view', en: 'View'},
  'Quay lại': {key: 'back', en: 'Back'},
  'Tiếp theo': {key: 'next', en: 'Next'},
  'Hoàn thành': {key: 'complete', en: 'Complete'},
  'Bắt đầu': {key: 'start', en: 'Start'},
  'Kết thúc': {key: 'end', en: 'End'},
  'Không có': {key: 'none', en: 'None'},
  'Đã xong': {key: 'done', en: 'Done'},
  'DONE': {key: 'doneUpper', en: 'DONE'},
  'Chờ xử lý': {key: 'pending', en: 'Pending'},
  'Đang chờ': {key: 'waiting', en: 'Waiting'},
  'Đã hoàn thành': {key: 'completed', en: 'Completed'},
  'Thành công': {key: 'success', en: 'Success'},
  'Thất bại': {key: 'failed', en: 'Failed'},
  'Cảnh báo': {key: 'warning', en: 'Warning'},
  'Thông báo': {key: 'notification', en: 'Notification'},
  'Xác nhận': {key: 'confirm', en: 'Confirm'},
  'Đặt lại': {key: 'reset', en: 'Reset'},
  'Làm mới': {key: 'refresh', en: 'Refresh'},
  'Cập nhật': {key: 'update', en: 'Update'},
  'Xem thêm': {key: 'seeMore', en: 'See more'},
  'Ẩn': {key: 'hide', en: 'Hide'},
  'Hiện': {key: 'show', en: 'Show'},
  'Bật': {key: 'enable', en: 'Enable'},
  'Tắt': {key: 'disable', en: 'Disable'},
  'Sắp xếp': {key: 'sort', en: 'Sort'},
  'Nhập': {key: 'input', en: 'Enter'},
  'Chọn ngày': {key: 'selectDate', en: 'Select date'},
  'Hôm nay': {key: 'today', en: 'Today'},
  'Tuần này': {key: 'thisWeek', en: 'This week'},
  'Tháng trước': {key: 'lastMonth', en: 'Last month'},
  'Giá': {key: 'price', en: 'Price'},
  'Hàng tồn kho': {key: 'inventoryStock', en: 'Inventory stock'},
  'Tên khách hàng': {key: 'customerName', en: 'Customer name'},
  'Ghi chú': {key: 'note', en: 'Note'},
  'LINH KIỆN': {key: 'partsUpper', en: 'PARTS'},
  'Linh kiện': {key: 'partsLabel', en: 'Parts'},
  'Đối tác': {key: 'partner', en: 'Partner'},
  'ĐỐI TÁC': {key: 'partnerUpper', en: 'PARTNER'},
  'Nhân viên kỹ thuật': {key: 'techStaff', en: 'Technician'},
  'Mã đơn': {key: 'orderCode', en: 'Order code'},
  'Mã máy': {key: 'deviceCode', en: 'Device code'},
  'Thiết bị': {key: 'device', en: 'Device'},
  'Model': {key: 'model', en: 'Model'},
  'Hãng': {key: 'brand', en: 'Brand'},
  'IMEI': {key: 'imei', en: 'IMEI'},
  'Vui lòng nhập': {key: 'pleaseEnter', en: 'Please enter'},
  'Bắt buộc': {key: 'required', en: 'Required'},
  'Tùy chọn': {key: 'optional', en: 'Optional'},
  'Đang tải...': {key: 'loading', en: 'Loading...'},
  'Không tìm thấy': {key: 'notFound', en: 'Not found'},
  'Mặc định': {key: 'defaultLabel', en: 'Default'},
  'Cài đặt': {key: 'settingsLabel', en: 'Settings'},
  'Thông tin': {key: 'info', en: 'Info'},
  'Tên cửa hàng': {key: 'shopName', en: 'Shop name'},
  'Địa chỉ cửa hàng': {key: 'shopAddress', en: 'Shop address'},
  'Giảm giá': {key: 'discount', en: 'Discount'},
  'Số dư': {key: 'balance', en: 'Balance'},
  'Chốt quỹ': {key: 'cashClosing', en: 'Cash closing'},
  'Báo cáo': {key: 'report', en: 'Report'},
  'Thống kê': {key: 'statistics', en: 'Statistics'},
  'Doanh thu': {key: 'revenueLabel', en: 'Revenue'},
  'Lãi gộp': {key: 'grossProfit', en: 'Gross profit'},
  'Chi phí': {key: 'expenseLabel', en: 'Expense'},
  'Lọc': {key: 'filterShort', en: 'Filter'},
  'Từ': {key: 'from', en: 'From'},
  'Đến': {key: 'to', en: 'To'},
  'Tất cả trạng thái': {key: 'allStatuses', en: 'All statuses'},
  'Tìm theo tên': {key: 'searchByName', en: 'Search by name'},
  'Đã hủy': {key: 'cancelled', en: 'Cancelled'},
  'Không có kết quả': {key: 'noResults', en: 'No results'},
  'Thêm mới': {key: 'addNew', en: 'Add new'},
  'Chỉnh sửa thông tin': {key: 'editInfo', en: 'Edit info'},
  'Xóa dữ liệu': {key: 'deleteData', en: 'Delete data'},
  'Xuất dữ liệu': {key: 'exportData', en: 'Export data'},
  'Nhập dữ liệu': {key: 'importData', en: 'Import data'},
  'Không có quyền': {key: 'noPermission', en: 'No permission'},
  'Bạn không có quyền truy cập tính năng này': {key: 'noAccessPermission', en: 'You do not have permission to access this feature'},
  'Vui lòng thử lại': {key: 'pleaseTryAgain', en: 'Please try again'},
  'Đã xảy ra lỗi': {key: 'errorOccurredLabel', en: 'An error occurred'},
  'Dữ liệu trống': {key: 'emptyData', en: 'Empty data'},
  'Không có đơn nào': {key: 'noOrders', en: 'No orders'},
  'Không có sản phẩm': {key: 'noProducts', en: 'No products'},
  'Không có khách hàng': {key: 'noCustomers', en: 'No customers'},
  'TẠO ĐƠN': {key: 'createOrder', en: 'CREATE ORDER'},
  'TẠO MỚI': {key: 'createNew', en: 'CREATE NEW'},
  'LINH KIỆN THAY': {key: 'partsReplaced', en: 'REPLACED PARTS'},
  'DỊCH VỤ SỬA': {key: 'repairService', en: 'REPAIR SERVICE'},
  'GHI CHÚ': {key: 'noteUpper', en: 'NOTE'},
  'Khách nợ': {key: 'customerDebt', en: 'Customer owes'},
  'Nợ NCC': {key: 'supplierDebtLabel', en: 'Owe supplier'},
  'Đã xóa': {key: 'deleted', en: 'Deleted'},
  'Hiện đang sử dụng': {key: 'currentlyUsing', en: 'Currently active'},
  'LINH KIỆN': {key: 'partsUpper', en: 'PARTS'},
  'giờ': {key: 'hourUnit', en: 'hr'},
};

// Build the final mapping
const mapping = {};
let usedExisting = 0;
let usedManual = 0;
let unmapped = 0;

for (const [viStr, freq] of viStrings) {
  // Check exact match in VI ARB
  if (viValueToKey[viStr]) {
    const k = viValueToKey[viStr];
    mapping[viStr] = {key: k, en: en[k] || viStr, vi: viStr, isNew: false, freq};
    usedExisting++;
  } else if (manual[viStr]) {
    mapping[viStr] = {...manual[viStr], vi: viStr, isNew: true, freq};
    usedManual++;
  } else {
    unmapped++;
    if (freq >= 3) {
      // Log unmapped strings with freq >= 3
      process.stderr.write(`UNMAPPED (${freq}x): ${viStr}\n`);
    }
  }
}

console.log(`Mapped: ${usedExisting} existing + ${usedManual} manual = ${usedExisting+usedManual}`);
console.log(`Unmapped: ${unmapped}`);
console.log(`Total unique: ${viStrings.length}`);

fs.writeFileSync('scripts/string_mapping.json', JSON.stringify(mapping, null, 2));
console.log('Written to scripts/string_mapping.json');
